# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rwGt1uoHSPHC-mwPhYWzlKGwtOUHAJdA
"""

class Solution(object):
    def removeOuterParentheses(self, S):
        """
        :type S: str
        :rtype: str
        """
        cnt = 0
        res = ''
        for i in range(len(S)):
            if S[i] == '(':
                cnt += 1
                if cnt > 1:
                    res += '('
            else:
                cnt -= 1
                if cnt != 0:
                    res += ')'
        return res